version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '10800:80'
    volumes:
      - .:/code
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    container_name: nginx_service
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project_managers.wsgi:application --bind 0.0.0.0:8000
    container_name: web_service
    volumes:
      - .:/code
      - ./static:/static
    expose:
      - '8000'
    depends_on:
      - mysql

  mysql:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: "saltlux#20"
      MYSQL_DATABASE: "equipments"
      MYSQL_USER: "donggyeong"
      MYSQL_PASSWORD: "shehdrud12"
    image: mysql
    ports:
      - "13306:3306"
    volumes:
      - ../volumes-mysql/mysql/:/var/lib/mysql/
