# Generated by Django 3.1.7 on 2021-03-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('', '직급 선택'), ('주임', '주임'), ('대리', '대리'), ('책임', '책임'), ('수석', '수석'), ('법인장님', '법인장님'), ('보관장소', '보관장소')], default='', max_length=20),
        ),
    ]
