# Generated by Django 3.1.7 on 2021-03-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipments', '0002_auto_20210308_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='created_at',
        ),
    ]
