# Generated by Django 3.1.7 on 2021-03-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipments', '0002_auto_20210308_0220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notebooks',
            new_name='Notebook',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
