# Generated by Django 3.1.7 on 2021-03-07 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipments', '0003_auto_20210308_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seat',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(34)]),
        ),
    ]
