# Generated by Django 3.1.7 on 2021-03-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipments', '0004_auto_20210308_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
