# Generated by Django 3.1.7 on 2021-03-07 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipments', '0004_auto_20210308_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', '종류 선택'), ('notebook_bag', 'notebook_bag'), ('hdmi', 'hdmi')], default='', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=20)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('', '용도 선택'), ('deep_learning', 'deep_learning'), ('offer_interface', 'offer_interface'), ('run_client_app', 'run_client_app')], default='', max_length=20)),
                ('cpu', models.CharField(blank=True, max_length=50)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('drive', models.CharField(blank=True, max_length=50)),
                ('gpu', models.CharField(blank=True, max_length=50)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', '종류 선택'), ('kiosk', 'kiosk')], default='', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=20)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalStroage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', '종류 선택'), ('nas', 'nas'), ('docking_station', 'docking_station'), ('external_hdd', 'external_hdd'), ('external_ssd', 'external_ssd')], default='', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=20)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('', '브랜드 선택'), ('logitech_old', 'logitech_old'), ('logitech_new', 'logitech_new'), ('mechanical', 'mechanical')], default='', max_length=20)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('', '브랜드 선택'), ('viewsync', 'viewsync'), ('lg', 'lg'), ('samsung_itech', 'samsung_itech'), ('samsung', 'samsung')], default='', max_length=20)),
                ('inch', models.IntegerField(blank=True, default=32)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('', '브랜드 선택'), ('logitech_old', 'logitech_old'), ('logitech_new', 'logitech_new'), ('gram', 'gram'), ('ultra', 'ultra'), ('samsung_itech', 'samsung_itech'), ('micronics', 'micronics')], default='', max_length=20)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', '종류 선택'), ('vpn_router', 'vpn_router'), ('hub', 'hub')], default='', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=20)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='SoundEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', '종류 선택'), ('microphone', 'microphone'), ('speaker', 'speaker')], default='', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=20)),
                ('purchase_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rank',
            field=models.CharField(choices=[('', '직급 선택'), ('s3', 's3'), ('s4', 's4'), ('s5', 's5'), ('s6', 's6'), ('s7', 's7'), ('s8', 's8'), ('freelancer', 'freelancer'), ('intern', 'intern'), ('contract', 'contract')], default='Not Ranked', max_length=20),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='brand',
            field=models.CharField(choices=[('', '브랜드 선택'), ('gram', 'gram'), ('ultra', 'ultra'), ('samsung_itech', 'samsung_itech'), ('asus', 'asus'), ('hansung', 'hansung')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('', '직급 선택'), ('s3', 's3'), ('s4', 's4'), ('s5', 's5'), ('s6', 's6'), ('s7', 's7'), ('s8', 's8'), ('freelancer', 'freelancer'), ('intern', 'intern'), ('contract', 'contract')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='seat',
            field=models.IntegerField(default=1),
        ),
    ]
