# Generated by Django 3.1.7 on 2021-03-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipments', '0007_auto_20210308_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seat',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
