# Generated by Django 3.1.7 on 2021-03-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipments', '0008_auto_20210312_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('', '직급 선택'), ('주임', '주임'), ('대리', '대리'), ('책임', '책임'), ('법인장님', '법인장님'), ('프리랜서', '프리랜서'), ('인턴', '인턴'), ('계약직', '계약직'), ('기타', '기타')], default='', max_length=20),
        ),
    ]
