# Generated by Django 3.1.7 on 2021-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipments', '0010_auto_20210313_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('type', 'brand')},
        ),
        migrations.AlterModelOptions(
            name='usage',
            options={'ordering': ('user_id', 'device_id')},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('seat', 'name')},
        ),
        migrations.AddField(
            model_name='device',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
